ALTER TABLE ACT_RU_EXECUTION ADD column IS_MI_ROOT_ TINYINT;

CREATE TABLE ACT_RU_ASYNC_JOB (
  ID_                  NVARCHAR(64)  NOT NULL,
  REV_                 INT,
  TYPE_                NVARCHAR(255) NOT NULL,
  LOCK_EXP_TIME_       DATETIME,
  LOCK_OWNER_          NVARCHAR(255),
  EXCLUSIVE_           BIT,
  EXECUTION_ID_        NVARCHAR(64),
  PROCESS_INSTANCE_ID_ NVARCHAR(64),
  PROC_DEF_ID_         NVARCHAR(64),
  RETRIES_             INT,
  EXCEPTION_STACK_ID_  NVARCHAR(64),
  EXCEPTION_MSG_       NVARCHAR(4000),
  HANDLER_TYPE_        NVARCHAR(255),
  HANDLER_CFG_         NVARCHAR(4000),
  TENANT_ID_           NVARCHAR(255) DEFAULT '',
  PRIMARY KEY (ID_)
);

CREATE TABLE ACT_RU_TIMER_JOB (
  ID_                  NVARCHAR(64)  NOT NULL,
  REV_                 INT,
  TYPE_                NVARCHAR(255) NOT NULL,
  LOCK_EXP_TIME_       DATETIME,
  LOCK_OWNER_          NVARCHAR(255),
  EXCLUSIVE_           BIT,
  EXECUTION_ID_        NVARCHAR(64),
  PROCESS_INSTANCE_ID_ NVARCHAR(64),
  PROC_DEF_ID_         NVARCHAR(64),
  RETRIES_             INT,
  EXCEPTION_STACK_ID_  NVARCHAR(64),
  EXCEPTION_MSG_       NVARCHAR(4000),
  DUEDATE_             DATETIME      NULL,
  REPEAT_              NVARCHAR(255),
  HANDLER_TYPE_        NVARCHAR(255),
  HANDLER_CFG_         NVARCHAR(4000),
  TENANT_ID_           NVARCHAR(255) DEFAULT '',
  SUSPENSION_STATE_    INTEGER,
  PRIMARY KEY (ID_)
);

ALTER TABLE ACT_RU_ASYNC_JOB
ADD CONSTRAINT ACT_FK_ASYNC_JOB_EXCEPTION
FOREIGN KEY (EXCEPTION_STACK_ID_)
REFERENCES ACT_GE_BYTEARRAY (ID_);

ALTER TABLE ACT_RU_TIMER_JOB
ADD CONSTRAINT ACT_FK_TIMER_JOB_EXCEPTION
FOREIGN KEY (EXCEPTION_STACK_ID_)
REFERENCES ACT_GE_BYTEARRAY (ID_);

-- Migrate data from old job table to the new format
SELECT *
INTO ACT_RU_ASYNC_JOB
FROM (SELECT
        ID_,
        REV_,
        TYPE_,
        GREATEST(DUEDATE_, LOCK_EXP_TIME_) AS LOCK_EXP_TIME_,
        LOCK_OWNER_,
        EXCLUSIVE_,
        EXECUTION_ID_,
        PROCESS_INSTANCE_ID_,
        PROC_DEF_ID_,
        RETRIES_,
        EXCEPTION_STACK_ID_,
        EXCEPTION_MSG_,
        HANDLER_TYPE_,
        HANDLER_CFG_,
        TENANT_ID_,
        NULL
      FROM ACT_RU_JOB
      WHERE TYPE_ LIKE 'message');

SELECT *
INTO ACT_RU_TIMER_JOB
FROM (SELECT
        ID_,
        REV_,
        TYPE_,
        LOCK_EXP_TIME_,
        LOCK_OWNER_,
        EXCLUSIVE_,
        EXECUTION_ID_,
        PROCESS_INSTANCE_ID_,
        PROC_DEF_ID_,
        RETRIES_,
        EXCEPTION_STACK_ID_,
        EXCEPTION_MSG_,
        DUEDATE_,
        REPEAT_,
        HANDLER_TYPE_,
        HANDLER_CFG_,
        TENANT_ID_,
        NULL
      FROM ACT_RU_JOB
      WHERE TYPE_ LIKE 'timer');

-- Delete old table
IF exists(SELECT TABLE_NAME
          FROM INFORMATION_SCHEMA.TABLES
          WHERE TABLE_NAME = 'ACT_RU_JOB')
  ALTER TABLE ACT_RU_JOB DROP CONSTRAINT ACT_FK_JOB_EXCEPTION;

IF exists(SELECT TABLE_NAME
          FROM INFORMATION_SCHEMA.TABLES
          WHERE TABLE_NAME = 'ACT_RU_JOB')
  DROP TABLE ACT_RU_JOB;

UPDATE ACT_GE_PROPERTY
SET VALUE_ = '6.0.0.1'
WHERE NAME_ = 'schema.version';
